### ISSUE TITLE
No module named 'api'

### ISSUE THREAD

**Issue by oesah** [matthiask/towel#17]
Hey, 

When I install the current version (0.8.1) i get the following error when trying to import from towel.api: ``No module named api``. There is no api module in the repo, but your documentation says I need to import API from towel.api. Is the documentation wrong or am I doing a mistake?

**Comment by matthiask** [comment]
Hey

The API code had not been updated in a while, was a bit broken and therefore been removed in 0.8 (see https://github.com/matthiask/towel/commit/35e5c9263f7bf69859386e20b40de834ec50d2cb). I'm sorry but I don't exactly remember what the problems were and whether they would be hard to fix.

**Comment by oesah** [comment]
Alright thanks, I removed the library completely and switched to other libs.

**Comment by matthiask** [comment]
Ok. I hope it didn't cause too much trouble!
